[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
application = { workspace = true }
domain = { workspace = true }
infrastructure = { workspace = true }
shared = { workspace = true }
dotenv = { workspace = true }
envy = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
env_logger = { workspace = true }

actix-web = "4.13.0"
actix-cors = "0.7.1"
validator = { version = "0.20", features = ["derive"] }
